### ISSUE TITLE
type object 'User' has no attribute 'get_not_used_port

### ISSUE THREAD

**Issue by qq516249940** [Ehco1996/django-sspanel#764]
按照前端教程操作：
https://ehco1996.github.io/django-sspanel/docs/panel/

```bash
root@ub-jack:/opt/django-sspanel# docker-compose run --rm web python manage.py migrate
Starting redis ... done
Starting mysql ... done

Operations to perform:
  Apply all migrations: admin, auth, contenttypes, proxy, sessions, sspanel, stats
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sspanel.0001_squashed_0055_auto_20200726_0847... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying proxy.0001_initial... OK
  Applying proxy.0002_auto_20201122_0831... OK
  Applying proxy.0003_relaynode_remark... OK
  Applying proxy.0004_auto_20210504_1420... OK
  Applying proxy.0005_auto_20210506_1950... OK
  Applying proxy.0006_auto_20210814_2144... OK
  Applying proxy.0007_relayrule_rule_name... OK
  Applying proxy.0008_auto_20211020_0821... OK
  Applying proxy.0009_auto_20220202_1243... OK
  Applying proxy.0010_auto_20220827_1555... OK
  Applying proxy.0011_auto_20220828_1040... OK
  Applying proxy.0012_auto_20220915_2040... OK
  Applying proxy.0013_proxynode_provider_remark... OK
  Applying proxy.0014_alter_trojanconfig_fallback_addr... OK
  Applying proxy.0015_alter_proxynode_server_alter_relaynode_server_and_more... OK
  Applying sessions.0001_initial... OK
  Applying sspanel.0002_auto_20200728_0821... OK
  Applying sspanel.0003_auto_20200729_0733... OK
  Applying sspanel.0004_auto_20201108_0400... OK
  Applying sspanel.0005_auto_20201110_2208... OK
  Applying sspanel.0006_auto_20201111_0742... OK
  Applying sspanel.0007_auto_20201122_0831... OK
  Applying sspanel.0008_auto_20210109_2036... OK
  Applying sspanel.0009_auto_20210131_0912... OK
  Applying sspanel.0010_delete_usersublog... OK
  Applying sspanel.0011_auto_20210504_1420... OK
  Applying sspanel.0012_user_uid... OK
  Applying sspanel.0013_remove_user_vmess_uuid... OK
  Applying sspanel.0014_ticket_updated_at... OK
  Applying sspanel.0015_usersocialprofile... OK
  Applying sspanel.0016_alter_usersocialprofile_user_id... OK
  Applying sspanel.0017_alter_usersocialprofile_options... OK
  Applying sspanel.0018_alter_usercheckinlog_date_alter_userreflog_date... OK
  Applying sspanel.0019_rename_ss_password_user_proxy_password_and_more... OK
  Applying stats.0001_initial... OK
  Applying stats.0002_alter_dailystats_id... OK
root@ub-jack:/opt/django-sspanel# docker-compose run --rm web python manage.py create_admin --email "admin@ss.com" --username "admin1" --password "adminadmin"
Starting redis ... done
Starting mysql ... done
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/apps/sspanel/management/commands/create_admin.py", line 43, in handle
    "ss_port": User.get_not_used_port(),
AttributeError: type object 'User' has no attribute 'get_not_used_port'
root@ub-jack:/opt/django-sspanel# docker-compose run --rm web python manage.py create_admin --email "admin@ss.com" --username "admin1" --password "adminadmin"
Starting redis ... done
Starting mysql ... done
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 88, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/apps/sspanel/management/commands/create_admin.py", line 43, in handle
    "ss_port": User.get_not_used_port(),
AttributeError: type object 'User' has no attribute 'get_not_used_port'

```

**Comment by Ehco1996** [comment]
this bug was introduced in https://github.com/Ehco1996/django-sspanel/commit/2ff8d9be8e0d0edb1b0c969a50a990f3709c79e3#diff-3ee2ce33d0a41cc01779469fec9a91cf248b34b2c9320b28cb4da11308afc291

**Comment by Ehco1996** [comment]
Anyone interested can try to fix the problem
